In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("hello world")
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [3]:
print(hello.numpy())

b'hello world'


In [8]:
from __future__ import print_function

In [9]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [10]:
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [11]:
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [13]:
# Matrix multiplikation
m1 = tf.constant([[1., 2.], [3. ,4.]]) # Dont forget [[ ]] cuz of matrix
m2 = tf.constant([[5., 6.], [7. ,8.]])

p = tf.matmul(m1, m2)
p

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [14]:
p.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)